// Self-host the typefaces.
//
// Linking fonts.googleapis.com means every person who opens the game makes a request to
// Google carrying their IP address and User-Agent, without being asked and without any
// benefit to them. It is the single most common privacy leak on the web, it is the only
// third-party request this project had, and a German court has already held it unlawful
// under the GDPR (LG München I, 3 O 17493/20).
//
// So the fonts ship with the game. Latin subsets only, woff2, four files. After this the
// page makes no third-party request of any kind and the README's claim that nothing is
// sent anywhere is simply true.
//
// Run: node tools/fetch-fonts.mjs   (only needed when the typefaces change)

import { writeFileSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FONTS = join(ROOT, 'fonts');
mkdirSync(FONTS, { recursive: true });

// A modern desktop UA, so Google serves woff2 rather than the legacy formats.
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const CSS = 'https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,600;9..144,700&family=IBM+Plex+Sans:wght@400;500;600&family=IBM+Plex+Mono:wght@400;500&display=swap';

const css = await (await fetch(CSS, { headers: { 'User-Agent': UA } })).text();

// Google emits one @font-face per family/weight/subset, each preceded by a /* subset */
// comment. We keep latin only, and deduplicate by URL: Fraunces and IBM Plex Sans are
// variable fonts, so every weight resolves to the same file and naively saving one copy
// per weight would triple the download for nothing.
const byUrl = new Map();
const blocks = css.split('@font-face').slice(1);
let pos = 0;
for (const raw of blocks) {
  const idx = css.indexOf('@font-face', pos);
  const subset = (css.slice(0, idx).match(/\/\*\s*([a-z0-9-]+)\s*\*\/\s*$/) || [])[1];
  pos = idx + 1;
  if (subset !== 'latin') continue;

  const family = (raw.match(/font-family:\s*'([^']+)'/) || [])[1];
  const weight = Number((raw.match(/font-weight:\s*([0-9]+)/) || [])[1] || 400);
  const style = (raw.match(/font-style:\s*(\w+)/) || [])[1] || 'normal';
  const url = (raw.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
  const range = (raw.match(/unicode-range:\s*([^;]+);/) || [])[1];
  if (!family || !url) continue;

  const key = url + '|' + style;
  if (byUrl.has(key)) {
    const f = byUrl.get(key);
    f.min = Math.min(f.min, weight);
    f.max = Math.max(f.max, weight);
    continue;
  }
  byUrl.set(key, { family, style, url, range, min: weight, max: weight });
}

const faces = [];
for (const f of byUrl.values()) {
  const slug = f.family.toLowerCase().replace(/\s+/g, '-');
  f.file = `${slug}-${f.min === f.max ? f.min : f.min + '-' + f.max}-${f.style}.woff2`;
  const buf = Buffer.from(await (await fetch(f.url, { headers: { 'User-Agent': UA } })).arrayBuffer());
  writeFileSync(join(FONTS, f.file), buf);
  console.log(`  ${f.file.padEnd(38)} ${(buf.length / 1024).toFixed(0)} KB  weight ${f.min === f.max ? f.min : f.min + '-' + f.max}`);
  faces.push({ ...f, weight: f.min === f.max ? String(f.min) : `${f.min} ${f.max}` });
}

const out = `/* Self-hosted so the page makes no third-party request. Generated by
   tools/fetch-fonts.mjs — edit that, not this. Latin subsets, woff2. */
${faces.map((f) => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('fonts/${f.file}') format('woff2');${f.range ? `\n  unicode-range: ${f.range};` : ''}
}`).join('\n')}
`;
writeFileSync(join(ROOT, 'fonts.css'), out);
console.log(`\nfonts.css — ${faces.length} faces, no external references`);
